<template>  
  <div class="relative w-full bg-main bg-fixed bg-no-repeat">
    <div class="flex flex-col h-screen overflow-y-scroll items-between relative w-full bg-black bg-opacity-75 mx-auto">
      <Header :page-theme-color="color" />
      <div :class="addThemeGradientColor" class="flex flex-col justify-between relative w-full pt-32 lg:pt-48 bg-gradient-to-b to-transparent h-full">
        <div class="relative w-full px-8 lg:px-32">
          <router-view @setColor="setColor"></router-view>

          <!-- Supplying range of theme colors to be generated by TailwindCSS during production build -->
          <!-- Background Colors -->
          <span class="hidden bg-red-100 bg-red-200 bg-red-300 bg-red-400 bg-red-500 bg-red-600 bg-red-700 bg-red-800 bg-red-900"></span>
          <span class="hidden bg-green-100 bg-green-200 bg-green-300 bg-green-400 bg-green-500 bg-green-600 bg-green-700 bg-green-800 bg-green-900"></span>
          <span class="hidden bg-blue-100 bg-blue-200 bg-blue-300 bg-blue-400 bg-blue-500 bg-blue-600 bg-blue-700 bg-blue-800 bg-blue-900"></span>
          <!-- Text Colors -->
          <span class="hidden text-red-100 text-red-200 text-red-300 text-red-400 text-red-500 text-red-600 text-red-700 text-red-800 text-red-900"></span>
          <span class="hidden text-green-100 text-green-200 text-green-300 text-green-400 text-green-500 text-green-600 text-green-700 text-green-800 text-green-900"></span>
          <span class="hidden text-blue-100 text-blue-200 text-blue-300 text-blue-400 text-blue-500 text-blue-600 text-blue-700 text-blue-800 text-blue-900"></span>
          <!-- Background Gradient Colors -->
          <span class="hidden from-red-100 from-red-200 from-red-300 from-red-400 from-red-500 from-red-600 from-red-700 from-red-800 from-red-900"></span>
          <span class="hidden from-green-100 from-green-200 from-green-300 from-green-400 from-green-500 from-green-600 from-green-700 from-green-800 from-green-900"></span>
          <span class="hidden from-blue-100 from-blue-200 from-blue-300 from-blue-400 from-blue-500 from-blue-600 from-blue-700 from-blue-800 from-blue-900"></span>
        </div>
        <Footer />
      </div>
    </div>    
  </div>
</template>

<script>

  import Header from './shared/Header'
  import Footer from './shared/Footer'

  export default {
    name: 'App',
    components: { Header, Footer },
    computed: {
      addThemeGradientColor() {
        return this.color ? `from-${this.color}-600` : ''
      }
    },
    props: {
      pageThemeColor: String,
    },
    data() {
      return {
        color: null
      }
    },
    methods: {
      setColor(value) {
        this.color = value
      }
    }
  }
</script>